'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { FiArrowRight, FiCheck, FiShoppingBag } from 'react-icons/fi'
import { DemoShell } from '../../components/DemoShell'

export default function StoreOwnerOnboardingPage() {
  const [step, setStep] = useState(1)
  const [complete, setComplete] = useState(false)
  function next(event: FormEvent) { event.preventDefault(); step < 3 ? setStep(step + 1) : setComplete(true) }
  if (complete) return <DemoShell active="Overview" showSidebar><div className="success-panel"><span className="success-icon"><FiCheck /></span><p className="eyebrow dark-eyebrow">Store profile saved</p><h1>Let&apos;s make every<br /><span>bike count.</span></h1><p>Your Demo Bike Co. store-owner profile is ready for verification. Customer bike registrations will link back to your store once approved.</p><div className="success-code">STORE OWNER ID <strong>STORE-DBCO-2026</strong></div><Link className="button button-green" href="/store-owner">Open store dashboard <FiArrowRight /></Link></div></DemoShell>
  return <DemoShell active="Overview" showSidebar><div className="role-form-layout"><div className="role-form-intro"><p className="eyebrow dark-eyebrow">Store owner onboarding</p><h1>Turn every<br /><span>sale into trust.</span></h1><p>Create your shop profile so customers can register their bikes with a trusted retail partner.</p><div className="role-trust-note"><FiShoppingBag /><span><strong>For bike shops &amp; retailers</strong><small>Link customer records to your verified store identity.</small></span></div></div><div className="form-card role-form-card"><div className="form-progress"><span className="active">01 Store</span><span className={step > 1 ? 'active' : ''}>02 Contact</span><span className={step > 2 ? 'active' : ''}>03 Review</span></div><form onSubmit={next}>{step === 1 && <><h2>Tell us about your store</h2><p className="form-helper">This creates the store owner record used for customer registrations.</p><label>Business name<input required defaultValue="Demo Bike Co." /></label><label>Store address<input required defaultValue="42 Long Street, Cape Town" /></label><label>Store status<select defaultValue="pending"><option value="pending">Pending verification</option><option value="verified">Verified store</option></select></label></>}{step === 2 && <><h2>Who should we contact?</h2><p className="form-helper">This person will manage your shop workspace.</p><label>Contact name<input required defaultValue="Kayla Morgan" /></label><label>Business email<input required type="email" defaultValue="hello@demobike.co.za" /></label><label>Phone number<input required type="tel" defaultValue="+27 82 555 0148" /></label></>}{step === 3 && <><h2>Review your store</h2><p className="form-helper">These details will be attached to the store owner record.</p><div className="review-list"><div><span>Business</span><strong>Demo Bike Co.</strong></div><div><span>Contact</span><strong>Kayla Morgan</strong></div><div><span>Address</span><strong>42 Long Street, Cape Town</strong></div><div><span>Status</span><strong>Pending verification</strong></div></div><label className="check-label"><input type="checkbox" required /> I confirm these store details are accurate.</label></>}<div className="form-actions"><button className="button button-green" type="submit">{step === 3 ? 'Create store profile' : 'Continue'} <FiArrowRight /></button>{step > 1 && <button className="text-button" type="button" onClick={() => setStep(step - 1)}>Back</button>}</div></form></div></div></DemoShell>
}
