'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { FiArrowRight, FiCheck, FiShield } from 'react-icons/fi'
import { DemoShell } from '../../components/DemoShell'

export default function InsurerOnboardingPage() {
  const [step, setStep] = useState(1)
  const [submitted, setSubmitted] = useState(false)
  function next(event: FormEvent) { event.preventDefault(); step < 3 ? setStep(step + 1) : setSubmitted(true) }
  if (submitted) return <DemoShell active="Overview" showSidebar><div className="success-panel"><span className="success-icon"><FiCheck /></span><p className="eyebrow dark-eyebrow">Partner application saved</p><h1>Welcome to the<br /><span>partner network.</span></h1><p>Your Horizon Cover workspace is ready for verification. In production, an administrator will approve the organisation and invite your team members.</p><div className="success-code">ORGANISATION ID <strong>ORG-HC-2026</strong></div><Link className="button button-green" href="/insurer">Open insurer dashboard <FiArrowRight /></Link></div></DemoShell>
  return <DemoShell active="Overview" showSidebar><div className="role-form-layout"><div className="role-form-intro"><p className="eyebrow dark-eyebrow">Insurer onboarding</p><h1>Bring better<br /><span>context to cover.</span></h1><p>Set up your organisation so your team can verify bikes, review policies and move claims forward.</p><div className="role-trust-note"><FiShield /><span><strong>Built for responsible access</strong><small>Organisation records are private and role-controlled.</small></span></div></div><div className="form-card role-form-card"><div className="form-progress"><span className="active">01 Organisation</span><span className={step > 1 ? 'active' : ''}>02 Your role</span><span className={step > 2 ? 'active' : ''}>03 Review</span></div><form onSubmit={next}>{step === 1 && <><h2>Tell us about the insurer</h2><p className="form-helper">This creates the organisation record in CycleTrace.</p><label>Organisation name<input required defaultValue="Horizon Cover" /></label><label>Organisation email<input required type="email" defaultValue="claims@horizoncover.co.za" /></label><label>Organisation status<select defaultValue="pending"><option value="pending">Pending verification</option><option value="active">Active partner</option></select></label></>}{step === 2 && <><h2>Set up your access</h2><p className="form-helper">Your membership controls which insurer tools you can use.</p><label>Full name<input required defaultValue="Kayla Morgan" /></label><label>Work email<input required type="email" defaultValue="kayla@horizoncover.co.za" /></label><label>Role<select defaultValue="admin"><option value="admin">Organisation admin</option><option value="reviewer">Verification reviewer</option><option value="claims">Claims specialist</option></select></label></>}{step === 3 && <><h2>Review your workspace</h2><p className="form-helper">These details will be attached to your insurer organisation and member records.</p><div className="review-list"><div><span>Organisation</span><strong>Horizon Cover</strong></div><div><span>Status</span><strong>Pending verification</strong></div><div><span>Member role</span><strong>Organisation admin</strong></div><div><span>Workspace</span><strong>Verification, policies &amp; claims</strong></div></div><label className="check-label"><input type="checkbox" required /> I confirm I represent this organisation.</label></>}<div className="form-actions"><button className="button button-green" type="submit">{step === 3 ? 'Create insurer workspace' : 'Continue'} <FiArrowRight /></button>{step > 1 && <button className="text-button" type="button" onClick={() => setStep(step - 1)}>Back</button>}</div></form></div></div></DemoShell>
}
