import Link from 'next/link'
import { notFound } from 'next/navigation'
import { DemoShell } from '../../components/DemoShell'
import { searchResults } from '../../lib/demo-data'

export default async function BikeDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const bike = searchResults.find(item => item.id === id)
  if (!bike) notFound()
  const stolen = bike.status === 'Reported stolen'
  return <DemoShell active="Search registry"><Link className="back-link" href="/search">← Back to search results</Link><div className="bike-detail-grid"><div><div className="detail-photo" style={{ backgroundImage: `url(${bike.image})` }}><span className={stolen ? 'status status-stolen' : 'status'}>{stolen ? '● Reported stolen' : '✓ Protected'}</span></div><div className="photo-caption">Public record · CycleTrace registry</div></div><div className="bike-detail-copy"><p className="eyebrow dark-eyebrow">Registry record · {bike.id.toUpperCase()}</p><h1>{bike.brand}<br /><span>{bike.model}</span></h1><p className="detail-intro">This bike has a public CycleTrace record. Confirm the serial number matches the frame before continuing with a purchase.</p><div className="detail-facts"><div><span>Serial number</span><strong>{bike.serial}</strong></div><div><span>Year</span><strong>{bike.year}</strong></div><div><span>Colour</span><strong>{bike.colour}</strong></div><div><span>Last known location</span><strong>{bike.location}</strong></div></div>{stolen ? <div className="alert-box alert-danger"><strong>This bike has been reported stolen.</strong><p>Do not purchase it. If you have information, contact the owner or report the listing to CycleTrace.</p><a href="mailto:reports@cycletrace.co.za">Report information →</a></div> : <div className="alert-box"><strong>Ownership record looks healthy.</strong><p>The record is active and no theft report is attached to this bike.</p></div>}<Link className="button button-dark" href="/register">Register your own bike <span>↗</span></Link></div></div><section className="detail-bottom"><div><p className="eyebrow dark-eyebrow">What to check</p><h2>A record is<br /><span>your first step.</span></h2></div><div className="check-grid"><div><strong>01</strong><h3>Match the number</h3><p>Find the serial number stamped on the frame and compare every character.</p></div><div><strong>02</strong><h3>Ask for ownership</h3><p>Request an invoice, registration email or another proof from the seller.</p></div><div><strong>03</strong><h3>Trust your gut</h3><p>If the price or story feels wrong, walk away and tell the community.</p></div></div></section></DemoShell>
}
