import { FiCheck, FiLock, FiSearch, FiShield, FiShoppingBag } from 'react-icons/fi'

export function PublicAboutSections() {
  return <>
    <section className="about-section section-shell" id="about" aria-labelledby="about-title"><div className="about-intro"><p className="eyebrow dark-eyebrow">One trusted record</p><h2 id="about-title">CycleTrace makes<br /><span>ownership visible.</span></h2><p>We connect riders, bike shops, insurers and communities around one simple idea: a bicycle is easier to protect when its identity and ownership are clear.</p></div><div className="about-principles"><div><span><FiShield /></span><h3>Protect before there&apos;s a problem</h3><p>Register the details that help prove your bike is yours before it ever goes missing.</p></div><div><span><FiSearch /></span><h3>Check before you commit</h3><p>Search a serial number before buying second-hand and make a more informed decision.</p></div><div><span><FiLock /></span><h3>Handle data responsibly</h3><p>POPIA-aligned principles guide what we collect, why we use it and who can access it.</p></div></div></section>
    <section className="services-section" id="services" aria-labelledby="services-title"><div className="section-shell"><div className="section-heading"><div><p className="eyebrow dark-eyebrow">One platform, four ways to help</p><h2 id="services-title">Built around<br /><span>the whole cycle.</span></h2></div><p>Whether you ride, sell, insure or recover bikes, CycleTrace gives you the right view of the same trusted record.</p></div><div className="services-grid"><article><span><FiShield /></span><h3>For riders</h3><p>Register bikes, keep ownership history, report theft and accept transfers safely.</p><a href="/register">Protect a bike <FiCheck /></a></article><article><span><FiShoppingBag /></span><h3>For store owners</h3><p>Register customer bikes at the point of sale and build trust into every handover.</p><a href="/store-owner/onboarding">Set up your store <FiCheck /></a></article><article><span><FiSearch /></span><h3>For insurers</h3><p>Verify serial numbers, review coverage records and bring better context to claims.</p><a href="/insurer/onboarding">Partner with us <FiCheck /></a></article><article><span><FiLock /></span><h3>For communities</h3><p>Give recovery partners a reliable way to identify bikes and connect them with owners.</p><a href="/organizations">Explore partnerships <FiCheck /></a></article></div></div></section>
    <section className="popia-strip section-shell" aria-labelledby="popia-title"><span className="popia-icon"><FiLock /></span><div><p className="eyebrow dark-eyebrow">Privacy by design</p><h2 id="popia-title">Your information is part of your protection.</h2><p>CycleTrace is designed around POPIA principles: collect only what is needed, explain how it is used, protect it carefully and keep control with the people and organisations who own the record.</p></div><a className="text-link dark-link" href="/privacy">Read our privacy approach <FiCheck /></a></section>
  </>
}
