'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { DemoShell } from '../../components/DemoShell'

export default function TransferPage() {
  const [step, setStep] = useState(1)
  const [complete, setComplete] = useState(false)
  function next(event: FormEvent) {
    event.preventDefault()
    if (step < 3) setStep(step + 1)
    else setComplete(true)
  }

  if (complete) return <DemoShell active="My bikes"><div className="success-panel"><span className="success-icon">✓</span><p className="eyebrow dark-eyebrow">Transfer initiated</p><h1>The bike is<br /><span>changing hands.</span></h1><p>We&apos;ve sent a transfer request to Jordan Lee. Your Specialized Allez Sport will remain in your account until they accept it.</p><div className="success-code">TRANSFER CODE <strong>TR-4826-JL</strong></div><div className="success-actions"><Link className="button button-green" href="/dashboard">Return to dashboard <span>→</span></Link><Link className="text-link dark-link" href="/dashboard">View transfer status <span>→</span></Link></div></div></DemoShell>

  return <DemoShell active="My bikes"><Link className="back-link" href="/dashboard">← Back to dashboard</Link><div className="transfer-layout"><div className="transfer-intro"><p className="eyebrow dark-eyebrow">Change of ownership</p><h1>Transfer a<br /><span>bike.</span></h1><p>Handing your bike to someone new? Keep its history intact and let the new owner take over the record.</p><div className="transfer-note"><span>✓</span><p><strong>What stays with the bike?</strong><br />Its serial number, registration history and any public recovery record.</p></div></div><div className="form-card transfer-card"><div className="form-progress"><span className={step >= 1 ? 'active' : ''}>01 Select bike</span><span className={step >= 2 ? 'active' : ''}>02 New owner</span><span className={step >= 3 ? 'active' : ''}>03 Confirm</span></div><form onSubmit={next}>{step === 1 && <><h2>Which bike are you transferring?</h2><p className="form-helper">The bike will stay protected while the new owner accepts.</p><div className="transfer-bike-option selected"><div className="mini-bike-photo" /><div><strong>Specialized Allez Sport</strong><span>WSBC6019K2482 · Protected</span></div><b>✓</b></div><div className="transfer-bike-option"><div className="mini-bike-photo trek" /><div><strong>Trek Marlin 7 Gen 3</strong><span>WTU178M4N11904 · Protected</span></div><b>○</b></div></>}{step === 2 && <><h2>Who are you transferring to?</h2><p className="form-helper">They&apos;ll get an email with a secure acceptance link.</p><label>New owner&apos;s full name<input required placeholder="e.g. Jordan Lee" /></label><label>New owner&apos;s email address<input required type="email" placeholder="jordan@example.com" /></label><label>Transfer date<input required type="date" /></label><label>Message <span className="optional">optional</span><textarea rows={3} placeholder="Add a note for the new owner..." /></label></>}{step === 3 && <><h2>Review the transfer</h2><p className="form-helper">Check these details before sending the request.</p><div className="review-list"><div><span>Bike</span><strong>Specialized Allez Sport</strong></div><div><span>New owner</span><strong>Jordan Lee</strong></div><div><span>Email</span><strong>jordan@example.com</strong></div><div><span>Record status</span><strong className="green-text">Protected until accepted</strong></div></div><label className="check-label"><input required type="checkbox" /> I confirm this is a legitimate transfer of ownership.</label></>}<div className="form-actions"><button className="button button-green" type="submit">{step === 3 ? 'Send transfer request' : 'Continue'} <span>→</span></button>{step > 1 && <button className="text-button" type="button" onClick={() => setStep(step - 1)}>Back</button>}</div></form></div></div></DemoShell>
}
