'use client'

import Link from 'next/link'
import { FormEvent, useState } from 'react'
import { DemoShell } from '../../components/DemoShell'

export default function ReportPage() {
  const [sent, setSent] = useState(false)
  if (sent) return <DemoShell active="My bikes"><div className="success-panel report-success"><span className="success-icon">✓</span><p className="eyebrow dark-eyebrow">Report received</p><h1>We&apos;re on<br /><span>the lookout.</span></h1><p>Your stolen bike report is now marked urgent in the CycleTrace registry. We&apos;ll email you when someone searches for a matching record.</p><div className="success-code">CASE NUMBER <strong>CT-2026-0914</strong></div><Link className="button button-green" href="/dashboard">Return to dashboard <span>→</span></Link></div></DemoShell>
  return <DemoShell active="My bikes"><Link className="back-link" href="/dashboard">← Back to dashboard</Link><div className="report-layout"><div className="report-intro"><p className="eyebrow dark-eyebrow">Urgent action</p><h1>Report a<br /><span>stolen bike.</span></h1><p>The sooner the community knows, the sooner they can help. This takes about two minutes.</p><div className="report-steps"><div className="active"><strong>01</strong><span>Tell us what happened</span></div><div><strong>02</strong><span>Confirm your details</span></div><div><strong>03</strong><span>Alert the community</span></div></div></div><div className="form-card report-card"><form onSubmit={(event: FormEvent) => { event.preventDefault(); setSent(true) }}><h2>What happened?</h2><p className="form-helper">We&apos;ve pre-filled your registered bike to make this quicker.</p><label>Bike to report<select defaultValue="Specialized Allez Sport"><option>Specialized Allez Sport · WSBC6019K2482</option><option>Trek Marlin 7 Gen 3 · WTU178M4N11904</option></select></label><label>When did it happen?<input required type="date" /></label><label>Where was it taken?<input required placeholder="Address, suburb or landmark" /></label><label>Police case number <span className="optional">optional</span><input placeholder="e.g. 2026/09/14/001" /></label><label>Anything else we should know?<textarea rows={3} placeholder="Colour, distinguishing marks, lock used..." /></label><label className="check-label"><input required type="checkbox" /> I confirm this information is accurate.</label><button className="button button-green full-button" type="submit">Submit stolen bike report <span>→</span></button></form></div></div></DemoShell>
}
